package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClienteDirecciones generated by hbm2java
 */
public class ClienteDirecciones  implements java.io.Serializable {


     private String id;
     private Byte idTipoDireccion;
     private String idCliente;
     private String idEmpresa;
     private String ciudad;
     private String descripcion;
     private String zipCode;
     private Boolean defecto;
     private char estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private Long trOrigen;
     private String sector;
     private String calle;
     private String casa;
     private String edificio;
     private String apartamento;
     private String municipio;

    public ClienteDirecciones() {
    }

	
    public ClienteDirecciones(String id, String ciudad, String descripcion, char estado, Date fechaInsercion, String usuarioInsercion) {
        this.id = id;
        this.ciudad = ciudad;
        this.descripcion = descripcion;
        this.estado = estado;
        this.fechaInsercion = fechaInsercion;
        this.usuarioInsercion = usuarioInsercion;
    }
    public ClienteDirecciones(String id, Byte idTipoDireccion, String ciudad, String descripcion, String zipCode, Boolean defecto, char estado, Date fechaInsercion, String usuarioInsercion, Date fechaActualizacion, String usuarioActualizacion, Long trOrigen, String sector, String calle, String casa, String edificio, String apartamento) {
       this.id = id;
       this.idTipoDireccion = idTipoDireccion;
       this.ciudad = ciudad;
       this.descripcion = descripcion;
       this.zipCode = zipCode;
       this.defecto = defecto;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.fechaActualizacion = fechaActualizacion;
       this.usuarioActualizacion = usuarioActualizacion;
       this.trOrigen = trOrigen;
       this.sector = sector;
       this.calle = calle;
       this.casa = casa;
       this.edificio = edificio;
       this.apartamento = apartamento;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Byte getIdTipoDireccion() {
        return this.idTipoDireccion;
    }
    
    public void setIdTipoDireccion(Byte idTipoDireccion) {
        this.idTipoDireccion = idTipoDireccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    public Boolean getDefecto() {
        return this.defecto;
    }
    
    public void setDefecto(Boolean defecto) {
        this.defecto = defecto;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getCasa() {
        return this.casa;
    }
    
    public void setCasa(String casa) {
        this.casa = casa;
    }
    public String getEdificio() {
        return this.edificio;
    }
    
    public void setEdificio(String edificio) {
        this.edificio = edificio;
    }
    public String getApartamento() {
        return this.apartamento;
    }
    
    public void setApartamento(String apartamento) {
        this.apartamento = apartamento;
    }

    /**
     * @return the idCliente
     */
    public String getIdCliente() {
        return idCliente;
    }

    /**
     * @param idCliente the idCliente to set
     */
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }

    /**
     * @return the idEmpresa
     */
    public String getIdEmpresa() {
        return idEmpresa;
    }

    /**
     * @param idEmpresa the idEmpresa to set
     */
    public void setIdEmpresa(String idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    /**
     * @return the municipio
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * @param municipio the municipio to set
     */
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }




}


