package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String id;
     private String id_empresa;
     private Empresa empresa;
     private String estadoCliente;
     private byte idTipoCliente;
     private BigDecimal limiteCredito;
     private char estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private String nombres;
     private String apellidos;
     private Short edad;
     private String sexo;
     private String estadoCivil;
     private String documentoIdentidad;
     private BigDecimal balanceCuenta;
     private String rnc;
     private String nombreEmpresa;
     private String contactoPrincipal;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private String idCondicion;
     private String nacionalidad;
     private String apodo;
     private String ocupacion;
     private String notas;
     private String pais;
     private Boolean valorFiscal;
     private String idTipoNcf;
     private String calDescDef;
     private String idMonedaDef;
     private Boolean idTipoIdent;
     private String idCentroCosto;
     private BigDecimal limiteFactPendCte;
     private Long trOrigen;
     private BigDecimal porcImpRetenido;
     private Boolean aplicaMora;
     private String cuentaContable;
     private String idCondicionVend;
     private String idClasificacion;
     private Boolean clientevip;
     private Long limteFactPendVenc;
     private Short descFactura;
     private BigDecimal limiteDescuento;
     private String idSubTipoCte;
     private String idEntidad;
     private String tipoEntidad;
     private String calificacionCte;
     private Character poseeTarjeta;
     private String bancoTarjeta;
     private Character poseeCuenta;
     private String bancoCuenta;
     private String referidoPor;
     private String idClienteReferido;
     private BigDecimal limiteMontoCuota;
     private String idTipoCategoria;
     private BigDecimal limiteDiasVen;
     private BigDecimal limitePorcInicial;
     private BigDecimal comisionVen;
     private String razonSocial;
     private String noPasaporte;
     private Set pedidoEncs = new HashSet(0);
     private Date fecha_nacimiento;

    public Cliente() {
    }

	
    public Cliente(String id, Empresa empresa, String estadoCliente, byte idTipoCliente, BigDecimal limiteCredito, char estado, Date fechaInsercion, String nombres, String idCondicion) {
        this.id = id;
        this.empresa = empresa;
        this.estadoCliente = estadoCliente;
        this.idTipoCliente = idTipoCliente;
        this.limiteCredito = limiteCredito;
        this.estado = estado;
        this.fechaInsercion = fechaInsercion;
        this.nombres = nombres;
        this.idCondicion = idCondicion;
    }
    public Cliente(String id, Empresa empresa, String estadoCliente, byte idTipoCliente, BigDecimal limiteCredito, char estado, Date fechaInsercion, String usuarioInsercion, String nombres, String apellidos, Short edad, String sexo, String estadoCivil, String documentoIdentidad, BigDecimal balanceCuenta, String rnc, String nombreEmpresa, String contactoPrincipal, Date fechaActualizacion, String usuarioActualizacion, String idCondicion, String nacionalidad, String apodo, String ocupacion, String notas, String pais, Boolean valorFiscal, String idTipoNcf, String calDescDef, String idMonedaDef, Boolean idTipoIdent, String idCentroCosto, BigDecimal limiteFactPendCte, Long trOrigen, BigDecimal porcImpRetenido, Boolean aplicaMora, String cuentaContable, String idCondicionVend, String idClasificacion, Boolean clientevip, Long limteFactPendVenc, Short descFactura, BigDecimal limiteDescuento, String idSubTipoCte, String idEntidad, String tipoEntidad, String calificacionCte, Character poseeTarjeta, String bancoTarjeta, Character poseeCuenta, String bancoCuenta, String referidoPor, String idClienteReferido, BigDecimal limiteMontoCuota, String idTipoCategoria, BigDecimal limiteDiasVen, BigDecimal limitePorcInicial, BigDecimal comisionVen, String razonSocial, String noPasaporte, Set pedidoEncs) {
       this.id = id;
       this.empresa = empresa;
       this.estadoCliente = estadoCliente;
       this.idTipoCliente = idTipoCliente;
       this.limiteCredito = limiteCredito;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.documentoIdentidad = documentoIdentidad;
       this.balanceCuenta = balanceCuenta;
       this.rnc = rnc;
       this.nombreEmpresa = nombreEmpresa;
       this.contactoPrincipal = contactoPrincipal;
       this.fechaActualizacion = fechaActualizacion;
       this.usuarioActualizacion = usuarioActualizacion;
       this.idCondicion = idCondicion;
       this.nacionalidad = nacionalidad;
       this.apodo = apodo;
       this.ocupacion = ocupacion;
       this.notas = notas;
       this.pais = pais;
       this.valorFiscal = valorFiscal;
       this.idTipoNcf = idTipoNcf;
       this.calDescDef = calDescDef;
       this.idMonedaDef = idMonedaDef;
       this.idTipoIdent = idTipoIdent;
       this.idCentroCosto = idCentroCosto;
       this.limiteFactPendCte = limiteFactPendCte;
       this.trOrigen = trOrigen;
       this.porcImpRetenido = porcImpRetenido;
       this.aplicaMora = aplicaMora;
       this.cuentaContable = cuentaContable;
       this.idCondicionVend = idCondicionVend;
       this.idClasificacion = idClasificacion;
       this.clientevip = clientevip;
       this.limteFactPendVenc = limteFactPendVenc;
       this.descFactura = descFactura;
       this.limiteDescuento = limiteDescuento;
       this.idSubTipoCte = idSubTipoCte;
       this.idEntidad = idEntidad;
       this.tipoEntidad = tipoEntidad;
       this.calificacionCte = calificacionCte;
       this.poseeTarjeta = poseeTarjeta;
       this.bancoTarjeta = bancoTarjeta;
       this.poseeCuenta = poseeCuenta;
       this.bancoCuenta = bancoCuenta;
       this.referidoPor = referidoPor;
       this.idClienteReferido = idClienteReferido;
       this.limiteMontoCuota = limiteMontoCuota;
       this.idTipoCategoria = idTipoCategoria;
       this.limiteDiasVen = limiteDiasVen;
       this.limitePorcInicial = limitePorcInicial;
       this.comisionVen = comisionVen;
       this.razonSocial = razonSocial;
       this.noPasaporte = noPasaporte;
       this.pedidoEncs = pedidoEncs;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getEstadoCliente() {
        return this.estadoCliente;
    }
    
    public void setEstadoCliente(String estadoCliente) {
        this.estadoCliente = estadoCliente;
    }
    public byte getIdTipoCliente() {
        return this.idTipoCliente;
    }
    
    public void setIdTipoCliente(byte idTipoCliente) {
        this.idTipoCliente = idTipoCliente;
    }
    public BigDecimal getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(BigDecimal limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Short getEdad() {
        return this.edad;
    }
    
    public void setEdad(Short edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getDocumentoIdentidad() {
        return this.documentoIdentidad;
    }
    
    public void setDocumentoIdentidad(String documentoIdentidad) {
        this.documentoIdentidad = documentoIdentidad;
    }
    public BigDecimal getBalanceCuenta() {
        return this.balanceCuenta;
    }
    
    public void setBalanceCuenta(BigDecimal balanceCuenta) {
        this.balanceCuenta = balanceCuenta;
    }
    public String getRnc() {
        return this.rnc;
    }
    
    public void setRnc(String rnc) {
        this.rnc = rnc;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getContactoPrincipal() {
        return this.contactoPrincipal;
    }
    
    public void setContactoPrincipal(String contactoPrincipal) {
        this.contactoPrincipal = contactoPrincipal;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public String getIdCondicion() {
        return this.idCondicion;
    }
    
    public void setIdCondicion(String idCondicion) {
        this.idCondicion = idCondicion;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getApodo() {
        return this.apodo;
    }
    
    public void setApodo(String apodo) {
        this.apodo = apodo;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getNotas() {
        return this.notas;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Boolean getValorFiscal() {
        return this.valorFiscal;
    }
    
    public void setValorFiscal(Boolean valorFiscal) {
        this.valorFiscal = valorFiscal;
    }
    public String getIdTipoNcf() {
        return this.idTipoNcf;
    }
    
    public void setIdTipoNcf(String idTipoNcf) {
        this.idTipoNcf = idTipoNcf;
    }
    public String getCalDescDef() {
        return this.calDescDef;
    }
    
    public void setCalDescDef(String calDescDef) {
        this.calDescDef = calDescDef;
    }
    public String getIdMonedaDef() {
        return this.idMonedaDef;
    }
    
    public void setIdMonedaDef(String idMonedaDef) {
        this.idMonedaDef = idMonedaDef;
    }
    public Boolean getIdTipoIdent() {
        return this.idTipoIdent;
    }
    
    public void setIdTipoIdent(Boolean idTipoIdent) {
        this.idTipoIdent = idTipoIdent;
    }
    public String getIdCentroCosto() {
        return this.idCentroCosto;
    }
    
    public void setIdCentroCosto(String idCentroCosto) {
        this.idCentroCosto = idCentroCosto;
    }
    public BigDecimal getLimiteFactPendCte() {
        return this.limiteFactPendCte;
    }
    
    public void setLimiteFactPendCte(BigDecimal limiteFactPendCte) {
        this.limiteFactPendCte = limiteFactPendCte;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
    public BigDecimal getPorcImpRetenido() {
        return this.porcImpRetenido;
    }
    
    public void setPorcImpRetenido(BigDecimal porcImpRetenido) {
        this.porcImpRetenido = porcImpRetenido;
    }
    public Boolean getAplicaMora() {
        return this.aplicaMora;
    }
    
    public void setAplicaMora(Boolean aplicaMora) {
        this.aplicaMora = aplicaMora;
    }
    public String getCuentaContable() {
        return this.cuentaContable;
    }
    
    public void setCuentaContable(String cuentaContable) {
        this.cuentaContable = cuentaContable;
    }
    public String getIdCondicionVend() {
        return this.idCondicionVend;
    }
    
    public void setIdCondicionVend(String idCondicionVend) {
        this.idCondicionVend = idCondicionVend;
    }
    public String getIdClasificacion() {
        return this.idClasificacion;
    }
    
    public void setIdClasificacion(String idClasificacion) {
        this.idClasificacion = idClasificacion;
    }
    public Boolean getClientevip() {
        return this.clientevip;
    }
    
    public void setClientevip(Boolean clientevip) {
        this.clientevip = clientevip;
    }
    public Long getLimteFactPendVenc() {
        return this.limteFactPendVenc;
    }
    
    public void setLimteFactPendVenc(Long limteFactPendVenc) {
        this.limteFactPendVenc = limteFactPendVenc;
    }
    public Short getDescFactura() {
        return this.descFactura;
    }
    
    public void setDescFactura(Short descFactura) {
        this.descFactura = descFactura;
    }
    public BigDecimal getLimiteDescuento() {
        return this.limiteDescuento;
    }
    
    public void setLimiteDescuento(BigDecimal limiteDescuento) {
        this.limiteDescuento = limiteDescuento;
    }
    public String getIdSubTipoCte() {
        return this.idSubTipoCte;
    }
    
    public void setIdSubTipoCte(String idSubTipoCte) {
        this.idSubTipoCte = idSubTipoCte;
    }
    public String getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(String idEntidad) {
        this.idEntidad = idEntidad;
    }
    public String getTipoEntidad() {
        return this.tipoEntidad;
    }
    
    public void setTipoEntidad(String tipoEntidad) {
        this.tipoEntidad = tipoEntidad;
    }
    public String getCalificacionCte() {
        return this.calificacionCte;
    }
    
    public void setCalificacionCte(String calificacionCte) {
        this.calificacionCte = calificacionCte;
    }
    public Character getPoseeTarjeta() {
        return this.poseeTarjeta;
    }
    
    public void setPoseeTarjeta(Character poseeTarjeta) {
        this.poseeTarjeta = poseeTarjeta;
    }
    public String getBancoTarjeta() {
        return this.bancoTarjeta;
    }
    
    public void setBancoTarjeta(String bancoTarjeta) {
        this.bancoTarjeta = bancoTarjeta;
    }
    public Character getPoseeCuenta() {
        return this.poseeCuenta;
    }
    
    public void setPoseeCuenta(Character poseeCuenta) {
        this.poseeCuenta = poseeCuenta;
    }
    public String getBancoCuenta() {
        return this.bancoCuenta;
    }
    
    public void setBancoCuenta(String bancoCuenta) {
        this.bancoCuenta = bancoCuenta;
    }
    public String getReferidoPor() {
        return this.referidoPor;
    }
    
    public void setReferidoPor(String referidoPor) {
        this.referidoPor = referidoPor;
    }
    public String getIdClienteReferido() {
        return this.idClienteReferido;
    }
    
    public void setIdClienteReferido(String idClienteReferido) {
        this.idClienteReferido = idClienteReferido;
    }
    public BigDecimal getLimiteMontoCuota() {
        return this.limiteMontoCuota;
    }
    
    public void setLimiteMontoCuota(BigDecimal limiteMontoCuota) {
        this.limiteMontoCuota = limiteMontoCuota;
    }
    public String getIdTipoCategoria() {
        return this.idTipoCategoria;
    }
    
    public void setIdTipoCategoria(String idTipoCategoria) {
        this.idTipoCategoria = idTipoCategoria;
    }
    public BigDecimal getLimiteDiasVen() {
        return this.limiteDiasVen;
    }
    
    public void setLimiteDiasVen(BigDecimal limiteDiasVen) {
        this.limiteDiasVen = limiteDiasVen;
    }
    public BigDecimal getLimitePorcInicial() {
        return this.limitePorcInicial;
    }
    
    public void setLimitePorcInicial(BigDecimal limitePorcInicial) {
        this.limitePorcInicial = limitePorcInicial;
    }
    public BigDecimal getComisionVen() {
        return this.comisionVen;
    }
    
    public void setComisionVen(BigDecimal comisionVen) {
        this.comisionVen = comisionVen;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getNoPasaporte() {
        return this.noPasaporte;
    }
    
    public void setNoPasaporte(String noPasaporte) {
        this.noPasaporte = noPasaporte;
    }
    public Set getPedidoEncs() {
        return this.pedidoEncs;
    }
    
    public void setPedidoEncs(Set pedidoEncs) {
        this.pedidoEncs = pedidoEncs;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the fecha_nacimiento
     */
    public Date getFecha_nacimiento() {
        return fecha_nacimiento;
    }

    /**
     * @param fecha_nacimiento the fecha_nacimiento to set
     */
    public void setFecha_nacimiento(Date fecha_nacimiento) {
        this.fecha_nacimiento = fecha_nacimiento;
    }




}


