package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String idEmpresa;
     private String nombreEmpresa;
     private String siglas;
     private String campo1;
     private String campo2;
     private String rnc;
     private char estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private String eslogan;
     private byte[] logoEmpresa;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private String colorFondo;
     private String colorRecordAct;
     private String colorItemAct;
     private Boolean personalizarColor;
     private Short mesPeriodoInicial;
     private String direccionWeb;
     private Boolean preciosConImpuestos;
     private Long trOrigen;
     private Date diaLabAnterior;
     private Date diaLabActual;
     private Date diaLabProximo;
     private BigDecimal diasLaborables;
     private String rutaFoto;
     private String idMetodoCosteo;
     private String campo3;
     private String idEstado;
     private String idCiudad;
     private String colorBarra;
     private String colorMenu;
     private String colorPantalla;
     private String colorItemMenu;
     private String colorItemBarra;
     private String colorItemPantalla;
     private String colorVentana;
     private String rutaLogo;
     private String colorVentanaEmerg;
     private Date fechaUltimaFacturacion;
     private Short diaFacturacion;
     private Set condicionPagos = new HashSet(0);
     private Set pedidoEncs = new HashSet(0);
     private Set centroCostoses = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String idEmpresa, String nombreEmpresa, char estado, Date fechaInsercion, String usuarioInsercion) {
        this.idEmpresa = idEmpresa;
        this.nombreEmpresa = nombreEmpresa;
        this.estado = estado;
        this.fechaInsercion = fechaInsercion;
        this.usuarioInsercion = usuarioInsercion;
    }
    public Empresa(String idEmpresa, String nombreEmpresa, String siglas, String campo1, String campo2, String rnc, char estado, Date fechaInsercion, String usuarioInsercion, String eslogan, byte[] logoEmpresa, Date fechaActualizacion, String usuarioActualizacion, String colorFondo, String colorRecordAct, String colorItemAct, Boolean personalizarColor, Short mesPeriodoInicial, String direccionWeb, Boolean preciosConImpuestos, Long trOrigen, Date diaLabAnterior, Date diaLabActual, Date diaLabProximo, BigDecimal diasLaborables, String rutaFoto, String idMetodoCosteo, String campo3, String idEstado, String idCiudad, String colorBarra, String colorMenu, String colorPantalla, String colorItemMenu, String colorItemBarra, String colorItemPantalla, String colorVentana, String rutaLogo, String colorVentanaEmerg, Date fechaUltimaFacturacion, Short diaFacturacion, Set condicionPagos, Set pedidoEncs, Set centroCostoses, Set clientes) {
       this.idEmpresa = idEmpresa;
       this.nombreEmpresa = nombreEmpresa;
       this.siglas = siglas;
       this.campo1 = campo1;
       this.campo2 = campo2;
       this.rnc = rnc;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.eslogan = eslogan;
       this.logoEmpresa = logoEmpresa;
       this.fechaActualizacion = fechaActualizacion;
       this.usuarioActualizacion = usuarioActualizacion;
       this.colorFondo = colorFondo;
       this.colorRecordAct = colorRecordAct;
       this.colorItemAct = colorItemAct;
       this.personalizarColor = personalizarColor;
       this.mesPeriodoInicial = mesPeriodoInicial;
       this.direccionWeb = direccionWeb;
       this.preciosConImpuestos = preciosConImpuestos;
       this.trOrigen = trOrigen;
       this.diaLabAnterior = diaLabAnterior;
       this.diaLabActual = diaLabActual;
       this.diaLabProximo = diaLabProximo;
       this.diasLaborables = diasLaborables;
       this.rutaFoto = rutaFoto;
       this.idMetodoCosteo = idMetodoCosteo;
       this.campo3 = campo3;
       this.idEstado = idEstado;
       this.idCiudad = idCiudad;
       this.colorBarra = colorBarra;
       this.colorMenu = colorMenu;
       this.colorPantalla = colorPantalla;
       this.colorItemMenu = colorItemMenu;
       this.colorItemBarra = colorItemBarra;
       this.colorItemPantalla = colorItemPantalla;
       this.colorVentana = colorVentana;
       this.rutaLogo = rutaLogo;
       this.colorVentanaEmerg = colorVentanaEmerg;
       this.fechaUltimaFacturacion = fechaUltimaFacturacion;
       this.diaFacturacion = diaFacturacion;
       this.condicionPagos = condicionPagos;
       this.pedidoEncs = pedidoEncs;
       this.centroCostoses = centroCostoses;
       this.clientes = clientes;
    }
   
    public String getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(String idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getSiglas() {
        return this.siglas;
    }
    
    public void setSiglas(String siglas) {
        this.siglas = siglas;
    }
    public String getCampo1() {
        return this.campo1;
    }
    
    public void setCampo1(String campo1) {
        this.campo1 = campo1;
    }
    public String getCampo2() {
        return this.campo2;
    }
    
    public void setCampo2(String campo2) {
        this.campo2 = campo2;
    }
    public String getRnc() {
        return this.rnc;
    }
    
    public void setRnc(String rnc) {
        this.rnc = rnc;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public String getEslogan() {
        return this.eslogan;
    }
    
    public void setEslogan(String eslogan) {
        this.eslogan = eslogan;
    }
    public byte[] getLogoEmpresa() {
        return this.logoEmpresa;
    }
    
    public void setLogoEmpresa(byte[] logoEmpresa) {
        this.logoEmpresa = logoEmpresa;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public String getColorFondo() {
        return this.colorFondo;
    }
    
    public void setColorFondo(String colorFondo) {
        this.colorFondo = colorFondo;
    }
    public String getColorRecordAct() {
        return this.colorRecordAct;
    }
    
    public void setColorRecordAct(String colorRecordAct) {
        this.colorRecordAct = colorRecordAct;
    }
    public String getColorItemAct() {
        return this.colorItemAct;
    }
    
    public void setColorItemAct(String colorItemAct) {
        this.colorItemAct = colorItemAct;
    }
    public Boolean getPersonalizarColor() {
        return this.personalizarColor;
    }
    
    public void setPersonalizarColor(Boolean personalizarColor) {
        this.personalizarColor = personalizarColor;
    }
    public Short getMesPeriodoInicial() {
        return this.mesPeriodoInicial;
    }
    
    public void setMesPeriodoInicial(Short mesPeriodoInicial) {
        this.mesPeriodoInicial = mesPeriodoInicial;
    }
    public String getDireccionWeb() {
        return this.direccionWeb;
    }
    
    public void setDireccionWeb(String direccionWeb) {
        this.direccionWeb = direccionWeb;
    }
    public Boolean getPreciosConImpuestos() {
        return this.preciosConImpuestos;
    }
    
    public void setPreciosConImpuestos(Boolean preciosConImpuestos) {
        this.preciosConImpuestos = preciosConImpuestos;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
    public Date getDiaLabAnterior() {
        return this.diaLabAnterior;
    }
    
    public void setDiaLabAnterior(Date diaLabAnterior) {
        this.diaLabAnterior = diaLabAnterior;
    }
    public Date getDiaLabActual() {
        return this.diaLabActual;
    }
    
    public void setDiaLabActual(Date diaLabActual) {
        this.diaLabActual = diaLabActual;
    }
    public Date getDiaLabProximo() {
        return this.diaLabProximo;
    }
    
    public void setDiaLabProximo(Date diaLabProximo) {
        this.diaLabProximo = diaLabProximo;
    }
    public BigDecimal getDiasLaborables() {
        return this.diasLaborables;
    }
    
    public void setDiasLaborables(BigDecimal diasLaborables) {
        this.diasLaborables = diasLaborables;
    }
    public String getRutaFoto() {
        return this.rutaFoto;
    }
    
    public void setRutaFoto(String rutaFoto) {
        this.rutaFoto = rutaFoto;
    }
    public String getIdMetodoCosteo() {
        return this.idMetodoCosteo;
    }
    
    public void setIdMetodoCosteo(String idMetodoCosteo) {
        this.idMetodoCosteo = idMetodoCosteo;
    }
    public String getCampo3() {
        return this.campo3;
    }
    
    public void setCampo3(String campo3) {
        this.campo3 = campo3;
    }
    public String getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(String idEstado) {
        this.idEstado = idEstado;
    }
    public String getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getColorBarra() {
        return this.colorBarra;
    }
    
    public void setColorBarra(String colorBarra) {
        this.colorBarra = colorBarra;
    }
    public String getColorMenu() {
        return this.colorMenu;
    }
    
    public void setColorMenu(String colorMenu) {
        this.colorMenu = colorMenu;
    }
    public String getColorPantalla() {
        return this.colorPantalla;
    }
    
    public void setColorPantalla(String colorPantalla) {
        this.colorPantalla = colorPantalla;
    }
    public String getColorItemMenu() {
        return this.colorItemMenu;
    }
    
    public void setColorItemMenu(String colorItemMenu) {
        this.colorItemMenu = colorItemMenu;
    }
    public String getColorItemBarra() {
        return this.colorItemBarra;
    }
    
    public void setColorItemBarra(String colorItemBarra) {
        this.colorItemBarra = colorItemBarra;
    }
    public String getColorItemPantalla() {
        return this.colorItemPantalla;
    }
    
    public void setColorItemPantalla(String colorItemPantalla) {
        this.colorItemPantalla = colorItemPantalla;
    }
    public String getColorVentana() {
        return this.colorVentana;
    }
    
    public void setColorVentana(String colorVentana) {
        this.colorVentana = colorVentana;
    }
    public String getRutaLogo() {
        return this.rutaLogo;
    }
    
    public void setRutaLogo(String rutaLogo) {
        this.rutaLogo = rutaLogo;
    }
    public String getColorVentanaEmerg() {
        return this.colorVentanaEmerg;
    }
    
    public void setColorVentanaEmerg(String colorVentanaEmerg) {
        this.colorVentanaEmerg = colorVentanaEmerg;
    }
    public Date getFechaUltimaFacturacion() {
        return this.fechaUltimaFacturacion;
    }
    
    public void setFechaUltimaFacturacion(Date fechaUltimaFacturacion) {
        this.fechaUltimaFacturacion = fechaUltimaFacturacion;
    }
    public Short getDiaFacturacion() {
        return this.diaFacturacion;
    }
    
    public void setDiaFacturacion(Short diaFacturacion) {
        this.diaFacturacion = diaFacturacion;
    }
    public Set getCondicionPagos() {
        return this.condicionPagos;
    }
    
    public void setCondicionPagos(Set condicionPagos) {
        this.condicionPagos = condicionPagos;
    }
    public Set getPedidoEncs() {
        return this.pedidoEncs;
    }
    
    public void setPedidoEncs(Set pedidoEncs) {
        this.pedidoEncs = pedidoEncs;
    }
    public Set getCentroCostoses() {
        return this.centroCostoses;
    }
    
    public void setCentroCostoses(Set centroCostoses) {
        this.centroCostoses = centroCostoses;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


