package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EstadoFactura generated by hbm2java
 */
public class EstadoFactura  implements java.io.Serializable {


     private char estadoFactura;
     private String descripcion;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private Character estado;
     private Long trOrigen;
     private Set pedidoEncs = new HashSet(0);

    public EstadoFactura() {
    }

	
    public EstadoFactura(char estadoFactura, Date fechaInsercion, String usuarioInsercion) {
        this.estadoFactura = estadoFactura;
        this.fechaInsercion = fechaInsercion;
        this.usuarioInsercion = usuarioInsercion;
    }
    public EstadoFactura(char estadoFactura, String descripcion, Date fechaInsercion, String usuarioInsercion, Date fechaActualizacion, String usuarioActualizacion, Character estado, Long trOrigen, Set pedidoEncs) {
       this.estadoFactura = estadoFactura;
       this.descripcion = descripcion;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.fechaActualizacion = fechaActualizacion;
       this.usuarioActualizacion = usuarioActualizacion;
       this.estado = estado;
       this.trOrigen = trOrigen;
       this.pedidoEncs = pedidoEncs;
    }
   
    public char getEstadoFactura() {
        return this.estadoFactura;
    }
    
    public void setEstadoFactura(char estadoFactura) {
        this.estadoFactura = estadoFactura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Long getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }
    public Set getPedidoEncs() {
        return this.pedidoEncs;
    }
    
    public void setPedidoEncs(Set pedidoEncs) {
        this.pedidoEncs = pedidoEncs;
    }




}


