package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ListaParametrosEnc generated by hbm2java
 */
public class ListaParametrosEnc  implements java.io.Serializable {


     private String id;
     private String descripcion;
     private String comentario;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private String id_empresa;
     private String id_clasificacion;

    public ListaParametrosEnc() {
    }

	
    public ListaParametrosEnc(String id) {
        this.id = id;
    }
    public ListaParametrosEnc(String id, String descripcion, String comentario, String estado, Date fechaInsercion, String usuarioInsercion, Set listaParametrosDets) {
       this.id = id;
       this.descripcion = descripcion;
       this.comentario = comentario;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;

    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the id_clasificacion
     */
    public String getId_clasificacion() {
        return id_clasificacion;
    }

    /**
     * @param id_clasificacion the id_clasificacion to set
     */
    public void setId_clasificacion(String id_clasificacion) {
        this.id_clasificacion = id_clasificacion;
    }




}


