package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ListaParametrosDet generated by hbm2java
 */
public class ListaParametrosDet  implements java.io.Serializable {


     private String id;
     private String id_empresa;
    
     private String listaParametrosEnc;
     private String descripcion;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private String etiqueta;
     private Integer orden;
     private BigDecimal idClasificacion;
     private String rutaImagen;

    public ListaParametrosDet() {
    }

	
    public ListaParametrosDet(String id, String listaParametrosEnc) {
        this.id = id;
        this.listaParametrosEnc = listaParametrosEnc;
    }
    public ListaParametrosDet(String id, String listaParametrosEnc, String descripcion, String estado, Date fechaInsercion, String usuarioInsercion, String etiqueta, Integer orden, BigDecimal idClasificacion, String rutaImagen) {
       this.id = id;
       this.listaParametrosEnc = listaParametrosEnc;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.etiqueta = etiqueta;
       this.orden = orden;
       this.idClasificacion = idClasificacion;
       this.rutaImagen = rutaImagen;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getListaParametrosEnc() {
        return this.listaParametrosEnc;
    }
    
    public void setListaParametrosEnc(String listaParametrosEnc) {
        this.listaParametrosEnc = listaParametrosEnc;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public String getEtiqueta() {
        return this.etiqueta;
    }
    
    public void setEtiqueta(String etiqueta) {
        this.etiqueta = etiqueta;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public BigDecimal getIdClasificacion() {
        return this.idClasificacion;
    }
    
    public void setIdClasificacion(BigDecimal idClasificacion) {
        this.idClasificacion = idClasificacion;
    }
    public String getRutaImagen() {
        return this.rutaImagen;
    }
    
    public void setRutaImagen(String rutaImagen) {
        this.rutaImagen = rutaImagen;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }




}


