package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PedidoEnc generated by hbm2java
 */
public class PedidoEnc implements java.io.Serializable {

    private String id;
    private String id_empresa;
    private String id_centroCostos;
    private String cliente;
    private String id_documento;
    private String estadoFactura;
    private String tipoTransaccion;
    private String nombreCliente;
    private String apellidosCte;
    private BigDecimal montoBruto;
    private BigDecimal montoNeto;
    private BigDecimal porcDescuento;
    private BigDecimal montoDesc;
    private BigDecimal montoImpuestos;
    private BigDecimal montoGravado;
    private BigDecimal montoExento;
    private String estado;
    private Date fechaInsercion;
    private String usuarioInsercion;
    private String idAsesor;
    private String notas;
    private Date fechaActualizacion;
    private String usuarioActualizacion;
    private String idCondicion;
    private BigDecimal tasaMoneda;
    private String idMoneda;
    private Long referencia;
    private String rnc;
    private Date fechaDocumento;
    private BigDecimal montoExonerado;
    private String calDesc;
    private BigDecimal tasaExoneracion;
    private BigDecimal tasaImp;
    private Date fechaVenc;
    private String impresion;
    private Date fechaDespacho;
    private String idMecanico;
    private Long trOrigen;
    private BigDecimal montoInicial;
    private Integer noPagos;
    private Boolean efectivo;
    private Boolean cheque;
    private Boolean tarjeta;
    private String idTipoTransFac;
    private String idDocumentoFac;
    private BigDecimal montoCuota;
    private String idTipoNcf;
    private String noTransaccion;
    private Boolean tipoFt;
    private String notaDescuento;
    private String noOrden;
    private Date fechaPedido;
    private String codTransporte;
    private Date fechaEnvio;
    private Short numeroDias;
    private Date fechaRealizacion;
    private BigDecimal montoAdicionales;
    private Character recibirVehiculo;
    private Character tipoFactura;
    private String idTipoServicio;
    private String idSupervisor;
    private Short dias;
    private Date fechaAnulacion;
    private String idPersonalFacturador;
    private BigDecimal devuelta;
    private Boolean autOrdenCompra;
    private String recibidoPor;
    private String realizadoPor;
    private Character ultimoFlujoComp;
    private Short numeroDiasPe;
    private Date fechaRealizacionPe;
    private Integer noPagosPe;
    private BigDecimal montoPe;
    private BigDecimal valorCuota;
    private Date fechaPrestamo;
    private String idOferta;
    private Character tipoTasaMoneda;

    public PedidoEnc() {
    }

    public PedidoEnc(String id, String cliente, String estadoFactura, String tipoTransaccion, BigDecimal montoBruto, BigDecimal montoNeto, BigDecimal montoDesc, BigDecimal montoImpuestos, BigDecimal montoGravado, BigDecimal montoExento, String estado, Date fechaInsercion, String usuarioInsercion, String idCondicion) {
        this.id = id;
        this.cliente = cliente;
        this.estadoFactura = estadoFactura;
        this.tipoTransaccion = tipoTransaccion;
        this.montoBruto = montoBruto;
        this.montoNeto = montoNeto;
        this.montoDesc = montoDesc;
        this.montoImpuestos = montoImpuestos;
        this.montoGravado = montoGravado;
        this.montoExento = montoExento;
        this.estado = estado;
        this.fechaInsercion = fechaInsercion;
        this.usuarioInsercion = usuarioInsercion;
        this.idCondicion = idCondicion;
    }

    public PedidoEnc(String id, String cliente,EstadoFactura String, String tipoTransaccion, String nombreCliente, String apellidosCte, BigDecimal montoBruto, BigDecimal montoNeto, BigDecimal porcDescuento, BigDecimal montoDesc, BigDecimal montoImpuestos, BigDecimal montoGravado, BigDecimal montoExento, String estado, Date fechaInsercion, String usuarioInsercion, String idAsesor, String notas, Date fechaActualizacion, String usuarioActualizacion, String idCondicion, BigDecimal tasaMoneda, String idMoneda, Long referencia, String rnc, Date fechaDocumento, BigDecimal montoExonerado, String calDesc, BigDecimal tasaExoneracion, BigDecimal tasaImp, Date fechaVenc, String impresion, Date fechaDespacho, String idMecanico, Long trOrigen, BigDecimal montoInicial, Integer noPagos, Boolean efectivo, Boolean cheque, Boolean tarjeta, String idTipoTransFac, String idDocumentoFac, BigDecimal montoCuota, String idTipoNcf, String noTransaccion, Boolean tipoFt, String notaDescuento, String noOrden, Date fechaPedido, String codTransporte, Date fechaEnvio, Short numeroDias, Date fechaRealizacion, BigDecimal montoAdicionales, Character recibirVehiculo, Character tipoFactura, String idTipoServicio, String idSupervisor, Short dias, Date fechaAnulacion, String idPersonalFacturador, BigDecimal devuelta, Boolean autOrdenCompra, String recibidoPor, String realizadoPor, Character ultimoFlujoComp, Short numeroDiasPe, Date fechaRealizacionPe, Integer noPagosPe, BigDecimal montoPe, BigDecimal valorCuota, Date fechaPrestamo, String idOferta, Character tipoTasaMoneda) {
        this.id = id;
        this.cliente = cliente;
        this.estadoFactura = estadoFactura;
        this.tipoTransaccion = tipoTransaccion;
        this.nombreCliente = nombreCliente;
        this.apellidosCte = apellidosCte;
        this.montoBruto = montoBruto;
        this.montoNeto = montoNeto;
        this.porcDescuento = porcDescuento;
        this.montoDesc = montoDesc;
        this.montoImpuestos = montoImpuestos;
        this.montoGravado = montoGravado;
        this.montoExento = montoExento;
        this.estado = estado;
        this.fechaInsercion = fechaInsercion;
        this.usuarioInsercion = usuarioInsercion;
        this.idAsesor = idAsesor;
        this.notas = notas;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
        this.idCondicion = idCondicion;
        this.tasaMoneda = tasaMoneda;
        this.idMoneda = idMoneda;
        this.referencia = referencia;
        this.rnc = rnc;
        this.fechaDocumento = fechaDocumento;
        this.montoExonerado = montoExonerado;
        this.calDesc = calDesc;
        this.tasaExoneracion = tasaExoneracion;
        this.tasaImp = tasaImp;
        this.fechaVenc = fechaVenc;
        this.impresion = impresion;
        this.fechaDespacho = fechaDespacho;
        this.idMecanico = idMecanico;
        this.trOrigen = trOrigen;
        this.montoInicial = montoInicial;
        this.noPagos = noPagos;
        this.efectivo = efectivo;
        this.cheque = cheque;
        this.tarjeta = tarjeta;
        this.idTipoTransFac = idTipoTransFac;
        this.idDocumentoFac = idDocumentoFac;
        this.montoCuota = montoCuota;
        this.idTipoNcf = idTipoNcf;
        this.noTransaccion = noTransaccion;
        this.tipoFt = tipoFt;
        this.notaDescuento = notaDescuento;
        this.noOrden = noOrden;
        this.fechaPedido = fechaPedido;
        this.codTransporte = codTransporte;
        this.fechaEnvio = fechaEnvio;
        this.numeroDias = numeroDias;
        this.fechaRealizacion = fechaRealizacion;
        this.montoAdicionales = montoAdicionales;
        this.recibirVehiculo = recibirVehiculo;
        this.tipoFactura = tipoFactura;
        this.idTipoServicio = idTipoServicio;
        this.idSupervisor = idSupervisor;
        this.dias = dias;
        this.fechaAnulacion = fechaAnulacion;
        this.idPersonalFacturador = idPersonalFacturador;
        this.devuelta = devuelta;
        this.autOrdenCompra = autOrdenCompra;
        this.recibidoPor = recibidoPor;
        this.realizadoPor = realizadoPor;
        this.ultimoFlujoComp = ultimoFlujoComp;
        this.numeroDiasPe = numeroDiasPe;
        this.fechaRealizacionPe = fechaRealizacionPe;
        this.noPagosPe = noPagosPe;
        this.montoPe = montoPe;
        this.valorCuota = valorCuota;
        this.fechaPrestamo = fechaPrestamo;
        this.idOferta = idOferta;
        this.tipoTasaMoneda = tipoTasaMoneda;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCliente() {
        return this.cliente;
    }

    public void setCliente(String cliente) {
        this.cliente = cliente;
    }



    public String getEstadoFactura() {
        return this.estadoFactura;
    }

    public void setEstadoFactura(String estadoFactura) {
        this.estadoFactura = estadoFactura;
    }

    public String getTipoTransaccion() {
        return this.tipoTransaccion;
    }

    public void setTipoTransaccion(String tipoTransaccion) {
        this.tipoTransaccion = tipoTransaccion;
    }

    public String getNombreCliente() {
        return this.nombreCliente;
    }

    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }

    public String getApellidosCte() {
        return this.apellidosCte;
    }

    public void setApellidosCte(String apellidosCte) {
        this.apellidosCte = apellidosCte;
    }

    public BigDecimal getMontoBruto() {
        return this.montoBruto;
    }

    public void setMontoBruto(BigDecimal montoBruto) {
        this.montoBruto = montoBruto;
    }

    public BigDecimal getMontoNeto() {
        return this.montoNeto;
    }

    public void setMontoNeto(BigDecimal montoNeto) {
        this.montoNeto = montoNeto;
    }

    public BigDecimal getPorcDescuento() {
        return this.porcDescuento;
    }

    public void setPorcDescuento(BigDecimal porcDescuento) {
        this.porcDescuento = porcDescuento;
    }

    public BigDecimal getMontoDesc() {
        return this.montoDesc;
    }

    public void setMontoDesc(BigDecimal montoDesc) {
        this.montoDesc = montoDesc;
    }

    public BigDecimal getMontoImpuestos() {
        return this.montoImpuestos;
    }

    public void setMontoImpuestos(BigDecimal montoImpuestos) {
        this.montoImpuestos = montoImpuestos;
    }

    public BigDecimal getMontoGravado() {
        return this.montoGravado;
    }

    public void setMontoGravado(BigDecimal montoGravado) {
        this.montoGravado = montoGravado;
    }

    public BigDecimal getMontoExento() {
        return this.montoExento;
    }

    public void setMontoExento(BigDecimal montoExento) {
        this.montoExento = montoExento;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }

    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }

    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }

    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }

    public String getIdAsesor() {
        return this.idAsesor;
    }

    public void setIdAsesor(String idAsesor) {
        this.idAsesor = idAsesor;
    }

    public String getNotas() {
        return this.notas;
    }

    public void setNotas(String notas) {
        this.notas = notas;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    public String getIdCondicion() {
        return this.idCondicion;
    }

    public void setIdCondicion(String idCondicion) {
        this.idCondicion = idCondicion;
    }

    public BigDecimal getTasaMoneda() {
        return this.tasaMoneda;
    }

    public void setTasaMoneda(BigDecimal tasaMoneda) {
        this.tasaMoneda = tasaMoneda;
    }

    public String getIdMoneda() {
        return this.idMoneda;
    }

    public void setIdMoneda(String idMoneda) {
        this.idMoneda = idMoneda;
    }

    public Long getReferencia() {
        return this.referencia;
    }

    public void setReferencia(Long referencia) {
        this.referencia = referencia;
    }

    public String getRnc() {
        return this.rnc;
    }

    public void setRnc(String rnc) {
        this.rnc = rnc;
    }

    public Date getFechaDocumento() {
        return this.fechaDocumento;
    }

    public void setFechaDocumento(Date fechaDocumento) {
        this.fechaDocumento = fechaDocumento;
    }

    public BigDecimal getMontoExonerado() {
        return this.montoExonerado;
    }

    public void setMontoExonerado(BigDecimal montoExonerado) {
        this.montoExonerado = montoExonerado;
    }

    public String getCalDesc() {
        return this.calDesc;
    }

    public void setCalDesc(String calDesc) {
        this.calDesc = calDesc;
    }

    public BigDecimal getTasaExoneracion() {
        return this.tasaExoneracion;
    }

    public void setTasaExoneracion(BigDecimal tasaExoneracion) {
        this.tasaExoneracion = tasaExoneracion;
    }

    public BigDecimal getTasaImp() {
        return this.tasaImp;
    }

    public void setTasaImp(BigDecimal tasaImp) {
        this.tasaImp = tasaImp;
    }

    public Date getFechaVenc() {
        return this.fechaVenc;
    }

    public void setFechaVenc(Date fechaVenc) {
        this.fechaVenc = fechaVenc;
    }

    public String getImpresion() {
        return this.impresion;
    }

    public void setImpresion(String impresion) {
        this.impresion = impresion;
    }

    public Date getFechaDespacho() {
        return this.fechaDespacho;
    }

    public void setFechaDespacho(Date fechaDespacho) {
        this.fechaDespacho = fechaDespacho;
    }

    public String getIdMecanico() {
        return this.idMecanico;
    }

    public void setIdMecanico(String idMecanico) {
        this.idMecanico = idMecanico;
    }

    public Long getTrOrigen() {
        return this.trOrigen;
    }

    public void setTrOrigen(Long trOrigen) {
        this.trOrigen = trOrigen;
    }

    public BigDecimal getMontoInicial() {
        return this.montoInicial;
    }

    public void setMontoInicial(BigDecimal montoInicial) {
        this.montoInicial = montoInicial;
    }

    public Integer getNoPagos() {
        return this.noPagos;
    }

    public void setNoPagos(Integer noPagos) {
        this.noPagos = noPagos;
    }

    public Boolean getEfectivo() {
        return this.efectivo;
    }

    public void setEfectivo(Boolean efectivo) {
        this.efectivo = efectivo;
    }

    public Boolean getCheque() {
        return this.cheque;
    }

    public void setCheque(Boolean cheque) {
        this.cheque = cheque;
    }

    public Boolean getTarjeta() {
        return this.tarjeta;
    }

    public void setTarjeta(Boolean tarjeta) {
        this.tarjeta = tarjeta;
    }

    public String getIdTipoTransFac() {
        return this.idTipoTransFac;
    }

    public void setIdTipoTransFac(String idTipoTransFac) {
        this.idTipoTransFac = idTipoTransFac;
    }

    public String getIdDocumentoFac() {
        return this.idDocumentoFac;
    }

    public void setIdDocumentoFac(String idDocumentoFac) {
        this.idDocumentoFac = idDocumentoFac;
    }

    public BigDecimal getMontoCuota() {
        return this.montoCuota;
    }

    public void setMontoCuota(BigDecimal montoCuota) {
        this.montoCuota = montoCuota;
    }

    public String getIdTipoNcf() {
        return this.idTipoNcf;
    }

    public void setIdTipoNcf(String idTipoNcf) {
        this.idTipoNcf = idTipoNcf;
    }

    public String getNoTransaccion() {
        return this.noTransaccion;
    }

    public void setNoTransaccion(String noTransaccion) {
        this.noTransaccion = noTransaccion;
    }

    public Boolean getTipoFt() {
        return this.tipoFt;
    }

    public void setTipoFt(Boolean tipoFt) {
        this.tipoFt = tipoFt;
    }

    public String getNotaDescuento() {
        return this.notaDescuento;
    }

    public void setNotaDescuento(String notaDescuento) {
        this.notaDescuento = notaDescuento;
    }

    public String getNoOrden() {
        return this.noOrden;
    }

    public void setNoOrden(String noOrden) {
        this.noOrden = noOrden;
    }

    public Date getFechaPedido() {
        return this.fechaPedido;
    }

    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }

    public String getCodTransporte() {
        return this.codTransporte;
    }

    public void setCodTransporte(String codTransporte) {
        this.codTransporte = codTransporte;
    }

    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }

    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }

    public Short getNumeroDias() {
        return this.numeroDias;
    }

    public void setNumeroDias(Short numeroDias) {
        this.numeroDias = numeroDias;
    }

    public Date getFechaRealizacion() {
        return this.fechaRealizacion;
    }

    public void setFechaRealizacion(Date fechaRealizacion) {
        this.fechaRealizacion = fechaRealizacion;
    }

    public BigDecimal getMontoAdicionales() {
        return this.montoAdicionales;
    }

    public void setMontoAdicionales(BigDecimal montoAdicionales) {
        this.montoAdicionales = montoAdicionales;
    }

    public Character getRecibirVehiculo() {
        return this.recibirVehiculo;
    }

    public void setRecibirVehiculo(Character recibirVehiculo) {
        this.recibirVehiculo = recibirVehiculo;
    }

    public Character getTipoFactura() {
        return this.tipoFactura;
    }

    public void setTipoFactura(Character tipoFactura) {
        this.tipoFactura = tipoFactura;
    }

    public String getIdTipoServicio() {
        return this.idTipoServicio;
    }

    public void setIdTipoServicio(String idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }

    public String getIdSupervisor() {
        return this.idSupervisor;
    }

    public void setIdSupervisor(String idSupervisor) {
        this.idSupervisor = idSupervisor;
    }

    public Short getDias() {
        return this.dias;
    }

    public void setDias(Short dias) {
        this.dias = dias;
    }

    public Date getFechaAnulacion() {
        return this.fechaAnulacion;
    }

    public void setFechaAnulacion(Date fechaAnulacion) {
        this.fechaAnulacion = fechaAnulacion;
    }

    public String getIdPersonalFacturador() {
        return this.idPersonalFacturador;
    }

    public void setIdPersonalFacturador(String idPersonalFacturador) {
        this.idPersonalFacturador = idPersonalFacturador;
    }

    public BigDecimal getDevuelta() {
        return this.devuelta;
    }

    public void setDevuelta(BigDecimal devuelta) {
        this.devuelta = devuelta;
    }

    public Boolean getAutOrdenCompra() {
        return this.autOrdenCompra;
    }

    public void setAutOrdenCompra(Boolean autOrdenCompra) {
        this.autOrdenCompra = autOrdenCompra;
    }

    public String getRecibidoPor() {
        return this.recibidoPor;
    }

    public void setRecibidoPor(String recibidoPor) {
        this.recibidoPor = recibidoPor;
    }

    public String getRealizadoPor() {
        return this.realizadoPor;
    }

    public void setRealizadoPor(String realizadoPor) {
        this.realizadoPor = realizadoPor;
    }

    public Character getUltimoFlujoComp() {
        return this.ultimoFlujoComp;
    }

    public void setUltimoFlujoComp(Character ultimoFlujoComp) {
        this.ultimoFlujoComp = ultimoFlujoComp;
    }

    public Short getNumeroDiasPe() {
        return this.numeroDiasPe;
    }

    public void setNumeroDiasPe(Short numeroDiasPe) {
        this.numeroDiasPe = numeroDiasPe;
    }

    public Date getFechaRealizacionPe() {
        return this.fechaRealizacionPe;
    }

    public void setFechaRealizacionPe(Date fechaRealizacionPe) {
        this.fechaRealizacionPe = fechaRealizacionPe;
    }

    public Integer getNoPagosPe() {
        return this.noPagosPe;
    }

    public void setNoPagosPe(Integer noPagosPe) {
        this.noPagosPe = noPagosPe;
    }

    public BigDecimal getMontoPe() {
        return this.montoPe;
    }

    public void setMontoPe(BigDecimal montoPe) {
        this.montoPe = montoPe;
    }

    public BigDecimal getValorCuota() {
        return this.valorCuota;
    }

    public void setValorCuota(BigDecimal valorCuota) {
        this.valorCuota = valorCuota;
    }

    public Date getFechaPrestamo() {
        return this.fechaPrestamo;
    }

    public void setFechaPrestamo(Date fechaPrestamo) {
        this.fechaPrestamo = fechaPrestamo;
    }

    public String getIdOferta() {
        return this.idOferta;
    }

    public void setIdOferta(String idOferta) {
        this.idOferta = idOferta;
    }

    public Character getTipoTasaMoneda() {
        return this.tipoTasaMoneda;
    }

    public void setTipoTasaMoneda(Character tipoTasaMoneda) {
        this.tipoTasaMoneda = tipoTasaMoneda;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the id_centroCostos
     */
    public String getId_centroCostos() {
        return id_centroCostos;
    }

    /**
     * @param id_centroCostos the id_centroCostos to set
     */
    public void setId_centroCostos(String id_centroCostos) {
        this.id_centroCostos = id_centroCostos;
    }

    /**
     * @return the id_documento
     */
    public String getId_documento() {
        return id_documento;
    }

    /**
     * @param id_documento the id_documento to set
     */
    public void setId_documento(String id_documento) {
        this.id_documento = id_documento;
    }

}
