package Modelos;
// Generated mar 27, 2017 10:48:16 a.m. by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VehiculoDocumento generated by hbm2java
 */
public class VehiculoDocumento  implements java.io.Serializable {


     private String id;
     private String id_empresa;
     private String id_tipo_trans;
     private String rutaDocumento;
     private String nota;
     private String estado;
     private Date fechaInsercion;
     private String usuarioInsercion;
     private Date fechaActualizacion;
     private String usuarioActualizacion;
     private BigDecimal trOrigen;

    public VehiculoDocumento() {
    }

	
    public VehiculoDocumento(String id) {
        this.id = id;
    }
    public VehiculoDocumento(String id, String rutaDocumento, String nota, String estado, Date fechaInsercion, String usuarioInsercion, Date fechaActualizacion, String usuarioActualizacion, BigDecimal trOrigen) {
       this.id = id;
       this.rutaDocumento = rutaDocumento;
       this.nota = nota;
       this.estado = estado;
       this.fechaInsercion = fechaInsercion;
       this.usuarioInsercion = usuarioInsercion;
       this.fechaActualizacion = fechaActualizacion;
       this.usuarioActualizacion = usuarioActualizacion;
       this.trOrigen = trOrigen;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRutaDocumento() {
        return this.rutaDocumento;
    }
    
    public void setRutaDocumento(String rutaDocumento) {
        this.rutaDocumento = rutaDocumento;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }
    
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }
    public String getUsuarioInsercion() {
        return this.usuarioInsercion;
    }
    
    public void setUsuarioInsercion(String usuarioInsercion) {
        this.usuarioInsercion = usuarioInsercion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }
    
    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }
    public BigDecimal getTrOrigen() {
        return this.trOrigen;
    }
    
    public void setTrOrigen(BigDecimal trOrigen) {
        this.trOrigen = trOrigen;
    }

    /**
     * @return the id_empresa
     */
    public String getId_empresa() {
        return id_empresa;
    }

    /**
     * @param id_empresa the id_empresa to set
     */
    public void setId_empresa(String id_empresa) {
        this.id_empresa = id_empresa;
    }

    /**
     * @return the id_tipo_trans
     */
    public String getId_tipo_trans() {
        return id_tipo_trans;
    }

    /**
     * @param id_tipo_trans the id_tipo_trans to set
     */
    public void setId_tipo_trans(String id_tipo_trans) {
        this.id_tipo_trans = id_tipo_trans;
    }




}


